<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="CPC-skasa-DD8QS" failures="0" tests="1" name="TestExecute.Drybar_US.regressionTestcase.TEST_DGLD_DB_US_ST_030_Registeruser_Product_Back_in_Stock_Subscription" time="37.925" errors="1" timestamp="2 Apr 2025 19:11:30 GMT">
  <testcase classname="TestExecute.Drybar_US.regressionTestcase.TEST_DGLD_DB_US_ST_030_Registeruser_Product_Back_in_Stock_Subscription" name="Validate_Product_Back_in_Stock_Subscription" time="37.925">
    <error message="null" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: null
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.fail(Assert.java:101)
	at TestLib.Common.assertionCheckwithReport(Common.java:1515)
	at TestComponent.Drybar_US.GoldDrybarusHelper2.login_Drybar(GoldDrybarusHelper2.java:162)
	at TestExecute.Drybar_US.regressionTestcase.TEST_DGLD_DB_US_ST_030_Registeruser_Product_Back_in_Stock_Subscription.Validate_Product_Back_in_Stock_Subscription(TEST_DGLD_DB_US_ST_030_Registeruser_Product_Back_in_Stock_Subscription.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- Validate_Product_Back_in_Stock_Subscription -->
</testsuite> <!-- TestExecute.Drybar_US.regressionTestcase.TEST_DGLD_DB_US_ST_030_Registeruser_Product_Back_in_Stock_Subscription -->
